name: CICD - Build and Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'

      - name: Install Dependencies
        run: |
          go version
          make deps

      - name: Create dotenv
        run: cp ./.env-template ./.env

      - name: Build
        run: make build

      - name: Test
        run: make test
